name: Build and Push Docker image to ECR and Deploy to ECS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Run git_update.sh (optional, for build artifacts)
      - name: Run git_update.sh
        run: |
          if [ -f git_update.sh ]; then
            chmod +x git_update.sh
            ./git_update.sh
          else
            echo "git_update.sh not found, skipping"
          fi

      # Step 4: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Must be us-east-1

      # Step 5: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private

      # Step 6: Build and push Docker image
      - name: Build and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}  # build-your-own-radar
          IMAGE_TAG_LATEST: latest
          IMAGE_TAG_SHA: sha-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA

      # Step 7: Fetch and validate ECS task definition
      - name: Fetch ECS Task Definition
        run: |
          curl -f -o ecs-task-definition.json https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/ecs-task-definition.json || {
            echo "Error: Failed to fetch ecs-task-definition.json or file is missing in repository"
            exit 1
          }
          # Validate JSON and check for containerDefinitions
          jq '.containerDefinitions' ecs-task-definition.json > /dev/null || {
            echo "Error: ecs-task-definition.json is invalid or missing containerDefinitions"
            exit 1
          }

      # Step 8: Update ECS Task Definition
      - name: Update ECS Task Definition
        run: |
          jq '.containerDefinitions[0].image = "${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:sha-${{ github.sha }}"' ecs-task-definition.json > updated-task-definition.json

      # Step 9: Deploy to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: updated-task-definition.json
          service: build-your-own-radar-service-vxz5o9wv
          cluster: build-your-own-radar-cluster
          wait-for-service-stability: true
