name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu VM in GitHub Actions

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out your code to the GitHub runner

    # Step 2: Set up Docker Buildx (optional, allows building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Amazon ECR using AWS credentials from GitHub Secrets
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secret for AWS Access Key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secret for AWS Secret Access Key
        aws-region: ${{ secrets.AWS_REGION }}  # GitHub Secret for AWS region (e.g., us-east-1)

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ECR_REPO_URI }}:latest .  # Use the repository URI secret to tag the image

    # Step 5: Push Docker image to Amazon ECR
    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ECR_REPO_URI }}:latest  # Push the tagged image to ECR

